apiVersion: v1
kind: Service
metadata:
  name: get-country-code-service
spec:
  selector:
    app: get-country-code
  ports:
  - port: 5001
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-country-code
spec:
  selector:
    matchLabels:
      app: get-country-code
  replicas: 4
  template:
    metadata:
      labels:
        app: get-country-code
    spec:
      containers:
      - name: get-country-code
        image: aditya93/country-name-to-country-code:v0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000